/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * correcto.java
 *
 * Created on 25-jul-2016, 10:47:08
 */
package trans.gru.pc;

import CBD.CBD;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author GERALDO J
 */
public class correcto extends javax.swing.JFrame implements Runnable {
 private int x=0; int y=120,velocidad=30;
    Thread Hilo1,Hilo2;
    int a;
    CBD mysql = new CBD();
          Connection cn = (Connection) mysql.Conectar();
          Timer contador;
       
    /** Creates new form correcto */
    public correcto() {
      r();
        this.setUndecorated(true);
        initComponents();
      
         this.setSize(x,y);
       
         setLocationRelativeTo(null);
           contador = new Timer(100, new claseTimer());  
           
    contador.start();
      nombre(); 
   
    }
     public class claseTimer
    implements ActionListener
  {
    public claseTimer() {}
    
    public void actionPerformed(ActionEvent e)
    {
        correcto.this.a =correcto.this.ProgressBar.getValue();
     correcto.this.ProgressBar.setForeground(Color.red);
       if (correcto.this.a < 30)
      {
           
       correcto.this.a += 1;
        if (correcto.this.a <= 10)
        {
         
          
          
        }
        if ((correcto.this.a > 10) && (correcto.this.a <= 20))
        {
        
        }
        if ((correcto.this.a > 20) && (correcto.this.a <= 30))
        {
        
          
        
        }
       
    correcto.this.ProgressBar.setValue(correcto.this.a);
    
    
    }else{
           
            correcto.this.contador.stop();
       correcto.this.cerrar(); 
     
      
    }
        }}
     void r(){
             new Thread(new Principal()).start();
     }
  
void nombre(){
    try
       {
            Statement st = (Statement) cn.createStatement();
         ResultSet rs = st.executeQuery("SELECT * FROM rol  WHERE activo ='"+1+"'  AND   activo <>'"+0+"'  " );
         rs.last();
          
            
        

         int encontrado=rs.getRow();
         
         if(encontrado==1)
             
         {  
             
           String   SQL = " SELECT * FROM rol WHERE activo ='"+1+"' "; 
         
          Statement sv = null;
            sv = cn.createStatement();
            ResultSet rv = sv.executeQuery(SQL);
            rv.next(); 
           
         
        
         
          String cd1=(rv.getString("cedula")); 
         
           String   SQL2 = " SELECT * FROM usuarios WHERE cedula ='"+cd1+"' "; 
         
          Statement sv1 = null;
            sv1 = cn.createStatement();
            ResultSet rv1 = sv1.executeQuery(SQL2);
            rv1.next(); 
           
         
        
         
          String nom1=(rv1.getString("nombres")); 
         String ape2=(rv1.getString("apellidos")); 
         
         lbn.setText(nom1+" "+ape2);
         
          
          
          
            
           
            
         }
         
         
         else
         {
            JOptionPane.showMessageDialog(null,"0","ERROR", JOptionPane.ERROR_MESSAGE);
      
         }

         rs.close();
         st.close();
       }
       catch (Exception e)
      {
      }
       
   
  
      
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbn = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(149, 200, 248));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel1.setText("BIENVENIDO");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 10, 130, 22);

        lbn.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        lbn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbn);
        lbn.setBounds(10, 50, 230, 27);
        jPanel1.add(ProgressBar);
        ProgressBar.setBounds(10, 10, 0, 0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(correcto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(correcto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(correcto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(correcto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                  
                  new Thread(new correcto()).start();
            }
          
        
        });
        
        

          
        
    }
     void cerrar(){
        try{
       this.setVisible(true);
       for(int i=0;i<7;i++){
           Hilo1.sleep(velocidad);
           this.setSize(x,y);
           this.setLocationRelativeTo(null);
           x=x-40;
          if(x==100000){
           for(int j=0;j<6;j++){
           Hilo2.sleep(velocidad);
           this.setSize(x,y);
           this.setLocationRelativeTo(null);
           y=y-100;   
          } 
       }
       }
        }catch(InterruptedException e){
            
        } 
        this.dispose();
    }
    public void run(){
        try{
       this.setVisible(true);
       for(int i=0;i<7;i++){
           Hilo1.sleep(velocidad);
           this.setSize(x,y);
           this.setLocationRelativeTo(null);
           x=x+40;
          if(x==100000 ){
           for(int j=0;j<6;j++){
           Hilo2.sleep(velocidad);
           this.setSize(x,y);
           this.setLocationRelativeTo(null);
           y=y+100;   
          } 
       }
       }
        }catch(InterruptedException e){
            
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbn;
    // End of variables declaration//GEN-END:variables
}
