/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Principal.java
 *
 * Created on 06/01/2017, 06:51:08 PM
 */
package trans.gru.pc;
import CBD.CBD;
import java.awt.Image;
import java.io.File;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author GeAnJi
 */
public class Principal extends javax.swing.JFrame implements Runnable {
CBD cc= new CBD();
Connection cn= cc.Conectar();
private int x = 270;
  int y = 578;
  int velocidad = 30;
  int Accion = 1;
  int resp = 0;
  Thread Hilo1;
  Thread Hilo2;

Statement st = null; 
String a,c,d,b,e,f,cedu,SQL2,acti="1";
  String Hora,fech;
      
       public static String fechaActual1()
  {
    Date fecha = new Date();
    SimpleDateFormat formatoFecha = new SimpleDateFormat("    dd-MM-yyy");
    return formatoFecha.format(fecha);
  }
         
        void reloj()
  {
      String mp,ap;
     Calendar car=Calendar.getInstance();
    
     
      ap =String.valueOf( car.get(car.AM_PM));
     if(ap.equals("0")){
         mp="AM";
     }
     else{
         mp="PM";
     }
    Hora=car.get(car.HOUR)+":"+car.get(car.MINUTE)+":"+car.get(car.SECOND)+" "+mp;
   
  }
    /** Creates new form Principal */
    public Principal() {
        setUndecorated(true);
        initComponents();
         setSize(this.x, this.y);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
      jch.setEnabled(false);
      jcs.setEnabled(false);
      jcd.setEnabled(false);
      jcss.setEnabled(false);
      jcus.setEnabled(false);
     
      jre.setEnabled(false);
      
         txtS.setEnabled(false);   
       txtCS.setEnabled(false);   
       txtC.setEnabled(false);   
       txtD.setEnabled(false);   
        txtD1.setEnabled(false);   
         txtD2.setEnabled(false);   
        rol();
        reloj();
    }
    void rol(){
          try { 
     String SQL = "select * from rol WHERE activo= '"+1+"' "  ;
     
      Statement st = this.cn.createStatement();
      ResultSet rs = st.executeQuery(SQL);
                
      while (rs.next())
      {
        
       a= rs.getString("a");
       b= rs.getString("b");
       c= rs.getString("c");
       d= rs.getString("d");
        e= rs.getString("e");
       f= rs.getString("f");
       cedu= rs.getString("cedula");
       
        
        
         
      }
      if(a.equals("1")){
       txtS.setEnabled(true); 
     
      jcs.setEnabled(true);
     
      }
       if(b.equals("1")){
       txtCS.setEnabled(true);
      jcss.setEnabled(true);
     
      }
        if(c.equals("1")){
       txtC.setEnabled(true);
       jch.setEnabled(true);
     
      }
         if(d.equals("1")){
       txtD.setEnabled(true);
       jcd.setEnabled(true);
      }
           if(e.equals("1")){
       txtD1.setEnabled(true);   
       jr.setEnabled(true);
      }
         if(f.equals("1")){
       txtD2.setEnabled(true);
       jcus.setEnabled(true);
      }
 } catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Error");
        
    }   

}
    void fesal(){
    String fe="No registrado";    
     try
       {
        
 CBD cc0= new CBD();
Connection cn0= cc0.Conectar(); 

     Statement st0 = (Statement) cn0.createStatement();
 
         ResultSet rs = st0.executeQuery("SELECT * FROM ensa  WHERE ce ='"+cedu+"' AND  fecha='"+fe+"'");
         rs.last();

         int encontrado=rs.getRow();
        
         if(encontrado==1)
         {
        reloj(); 
        fechaActual1();

   
      fech=fechaActual1();   
          String   SQL4="UPDATE   ensa set  sa=?,fecha=? WHERE ce='"+cedu+"'AND fecha='"+fe+"' ";
    try{
        
         PreparedStatement psd4;
        psd4=cn.prepareStatement(SQL4);
       
        psd4.setString(1,Hora);
        psd4.setString(2,fech);
       
     
          
           
           int Up=psd4.executeUpdate();
           if(Up==1){
              
               JOptionPane.showMessageDialog(null,"Guardado");
           } 
            }catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Error");
        }
    } }catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Error");
        }
            }
  

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtS = new javax.swing.JButton();
        txtD = new javax.swing.JButton();
        txtCS = new javax.swing.JButton();
        txtC = new javax.swing.JButton();
        txtD1 = new javax.swing.JButton();
        txtD2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jch = new javax.swing.JMenuItem();
        jcs = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jcd = new javax.swing.JMenuItem();
        jcss = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jcus = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jusu = new javax.swing.JMenuItem();
        jre = new javax.swing.JMenuItem();
        jr = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jmu = new javax.swing.JMenuItem();
        jIn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(20, 136, 238));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtS.setBackground(new java.awt.Color(0, 0, 0));
        txtS.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtS.setText("GESTIÓN DE SERVICIO");
        txtS.setContentAreaFilled(false);
        txtS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtS.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        txtS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        txtS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSMouseEntered(evt);
            }
        });
        txtS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSActionPerformed(evt);
            }
        });

        txtD.setBackground(new java.awt.Color(0, 0, 0));
        txtD.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtD.setText("CONSULTA DE DINERO");
        txtD.setContentAreaFilled(false);
        txtD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtD.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        txtD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtDMouseEntered(evt);
            }
        });
        txtD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDActionPerformed(evt);
            }
        });

        txtCS.setBackground(new java.awt.Color(0, 0, 0));
        txtCS.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtCS.setText("CONSULTA DE SERVICIO");
        txtCS.setContentAreaFilled(false);
        txtCS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtCS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        txtCS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCSMouseEntered(evt);
            }
        });
        txtCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCSActionPerformed(evt);
            }
        });

        txtC.setBackground(new java.awt.Color(0, 0, 0));
        txtC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtC.setText("GESTIÓN DE CHOFERES");
        txtC.setContentAreaFilled(false);
        txtC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtC.setInheritsPopupMenu(true);
        txtC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        txtC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCMouseEntered(evt);
            }
        });
        txtC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCActionPerformed(evt);
            }
        });

        txtD1.setBackground(new java.awt.Color(0, 0, 0));
        txtD1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtD1.setText("GESTIÓN DE ROLES");
        txtD1.setContentAreaFilled(false);
        txtD1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtD1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtD1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        txtD1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtD1MouseEntered(evt);
            }
        });
        txtD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtD1ActionPerformed(evt);
            }
        });

        txtD2.setBackground(new java.awt.Color(0, 0, 0));
        txtD2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtD2.setForeground(new java.awt.Color(51, 51, 51));
        txtD2.setText("AUDITORIA DE USUARIOS");
        txtD2.setContentAreaFilled(false);
        txtD2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtD2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtD2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        txtD2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtD2MouseEntered(evt);
            }
        });
        txtD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtD2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtS, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtD2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(txtD1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(txtS, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCS, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtC, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtD, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtD1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(txtD2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SALIR-->");
        jButton1.setToolTipText("");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setPreferredSize(new java.awt.Dimension(800, 450));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(656, 656, 656)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu2.setText("GESTIÓN");

        jch.setText("Gestión de choferes");
        jch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchActionPerformed(evt);
            }
        });
        jMenu2.add(jch);

        jcs.setText("Gestión de servicios");
        jcs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcsActionPerformed(evt);
            }
        });
        jMenu2.add(jcs);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("CONSULTAS");

        jcd.setText("Consulta de dinero");
        jcd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcdActionPerformed(evt);
            }
        });
        jMenu1.add(jcd);

        jcss.setText("Consultas de servicio");
        jcss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcssActionPerformed(evt);
            }
        });
        jMenu1.add(jcss);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("AUDITORIA");

        jcus.setText("Auditoria de usuarios");
        jcus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcusActionPerformed(evt);
            }
        });
        jMenu3.add(jcus);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("SEGURIDAD");

        jusu.setText("Gestión de usuarios");
        jusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jusuActionPerformed(evt);
            }
        });
        jMenu4.add(jusu);

        jre.setText("Respaldo-Restauracion");
        jre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jreActionPerformed(evt);
            }
        });
        jMenu4.add(jre);

        jr.setText("Gestión de roles");
        jr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrActionPerformed(evt);
            }
        });
        jMenu4.add(jr);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("AYUDA");

        jmu.setText("Manual de usuario");
        jmu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmuActionPerformed(evt);
            }
        });
        jMenu6.add(jmu);

        jIn.setText("Información");
        jIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInActionPerformed(evt);
            }
        });
        jMenu6.add(jIn);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void txtSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSActionPerformed

 
    
    
    PreparedStatement psd1,psd2,psd4;
  
      SQL2="UPDATE actividades set activo=? WHERE cedula=? ";
try{
     psd1 = cn.prepareStatement(SQL2);
     psd1.setString(1,acti);
        psd1.setString(2,cedu);
       
          
      
      psd1.executeUpdate();
        } catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Error");
        
    }   
   
   GestionActividad d=new GestionActividad();
d.setVisible(true);

 SQL2="UPDATE actividades set activo=? WHERE cedula=? ";
try{
     psd2 = cn.prepareStatement(SQL2);
     psd2.setString(1,"0");
        psd2.setString(2,cedu);
       
          
      
      psd2.executeUpdate();
        } catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Error");
        
    }      
}//GEN-LAST:event_txtSActionPerformed

private void txtCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCActionPerformed
  PreparedStatement psd1,psd2,psd4;
  
      SQL2="UPDATE actividades set activo=? WHERE cedula=? ";
try{
     psd1 = cn.prepareStatement(SQL2);
     psd1.setString(1,acti);
        psd1.setString(2,cedu);
       
          
      
      psd1.executeUpdate();
        } catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Error");
        
    }   
   
    chofer1 d=new chofer1();
d.setVisible(true);

 SQL2="UPDATE actividades set activo=? WHERE cedula=? ";
try{
     psd2 = cn.prepareStatement(SQL2);
     psd2.setString(1,"0");
        psd2.setString(2,cedu);
       
          
      
      psd2.executeUpdate();
        } catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Error");
        
    }   
}//GEN-LAST:event_txtCActionPerformed

private void txtCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCSActionPerformed
 PreparedStatement psd1,psd2,psd4;
  
      SQL2="UPDATE actividades set activo=? WHERE cedula=? ";
try{
     psd1 = cn.prepareStatement(SQL2);
     psd1.setString(1,acti);
        psd1.setString(2,cedu);
       
          
      
      psd1.executeUpdate();
        } catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Error");
        
    }   
   
   CosultaServicio d=new CosultaServicio();
d.setVisible(true);

 SQL2="UPDATE actividades set activo=? WHERE cedula=? ";
try{
     psd2 = cn.prepareStatement(SQL2);
     psd2.setString(1,"0");
        psd2.setString(2,cedu);
       
          
      
      psd2.executeUpdate();
        } catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Error");
        
    }   // TODO add your handling code here:
}//GEN-LAST:event_txtCSActionPerformed

private void txtDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDActionPerformed
PreparedStatement psd1,psd2,psd4;
  
  
      SQL2="UPDATE actividades set activo=? WHERE cedula=? ";
try{
     psd1 = cn.prepareStatement(SQL2);
     psd1.setString(1,acti);
        psd1.setString(2,cedu);
       
          
      
      psd1.executeUpdate();
        } catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Error");
        
    }   
   
    ConsultaDinero d=new ConsultaDinero();
d.setVisible(true);

 SQL2="UPDATE actividades set activo=? WHERE cedula=? ";
try{
     psd2 = cn.prepareStatement(SQL2);
     psd2.setString(1,"0");
        psd2.setString(2,cedu);
       
          
      
      psd2.executeUpdate();
        } catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Error");
        
    }   
                        // TODO add your handling code here:
}//GEN-LAST:event_txtDActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
fesal();
dispose();
}//GEN-LAST:event_jButton1ActionPerformed

private void txtD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtD1ActionPerformed
 PreparedStatement psd1,psd2,psd4;
  
      SQL2="UPDATE actividades set activo=? WHERE cedula=? ";
try{
     psd1 = cn.prepareStatement(SQL2);
     psd1.setString(1,acti);
        psd1.setString(2,cedu);
       
          
      
      psd1.executeUpdate();
        } catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Error");
        
    }   
   
    control d=new control();
d.setVisible(true);

 SQL2="UPDATE actividades set activo=? WHERE cedula=? ";
try{
     psd2 = cn.prepareStatement(SQL2);
     psd2.setString(1,"0");
        psd2.setString(2,cedu);
       
          
      
      psd2.executeUpdate();
        } catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Error");
        
    } 
}//GEN-LAST:event_txtD1ActionPerformed

private void txtD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtD2ActionPerformed
 PreparedStatement psd1,psd2,psd4;
  
      SQL2="UPDATE actividades set activo=? WHERE cedula=? ";
try{
     psd1 = cn.prepareStatement(SQL2);
     psd1.setString(1,acti);
        psd1.setString(2,cedu);
       
          
      
      psd1.executeUpdate();
        } catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Error");
        
    }   
   
    auditoria1 d=new auditoria1();
d.setVisible(true);

 SQL2="UPDATE actividades set activo=? WHERE cedula=? ";
try{
     psd2 = cn.prepareStatement(SQL2);
     psd2.setString(1,"0");
        psd2.setString(2,cedu);
       
          
      
      psd2.executeUpdate();
        } catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Error");
        
    } // TODO add your handling code here:
}//GEN-LAST:event_txtD2ActionPerformed

private void txtSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSMouseEntered
   File ruta = new File("C:/Users/android/Documents/gg/4.png");
           
            String d=(String.valueOf(ruta));
          
            Image foto= getToolkit().getImage(d);
            
           
          
           jLabel1.setIcon(new ImageIcon(foto));
        // TODO add your handling code here:
}//GEN-LAST:event_txtSMouseEntered

private void txtCSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCSMouseEntered
 File ruta = new File("C:/Users/android/Documents/gg/5.png");
           
            String d=(String.valueOf(ruta));
          
            Image foto= getToolkit().getImage(d);
            
           
          
           jLabel1.setIcon(new ImageIcon(foto));// TODO add your handling code here:
}//GEN-LAST:event_txtCSMouseEntered

private void txtCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCMouseEntered
 File ruta = new File("C:/Users/android/Documents/gg/6.png");
           
            String d=(String.valueOf(ruta));
          
            Image foto= getToolkit().getImage(d);
            
           
          
           jLabel1.setIcon(new ImageIcon(foto));// TODO add your handling code here:
}//GEN-LAST:event_txtCMouseEntered

private void txtDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDMouseEntered
 File ruta = new File("C:/Users/android/Documents/gg/7.png");
           
            String d=(String.valueOf(ruta));
          
            Image foto= getToolkit().getImage(d);
            
           
          
           jLabel1.setIcon(new ImageIcon(foto));// TODO add your handling code here:
}//GEN-LAST:event_txtDMouseEntered

private void txtD1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtD1MouseEntered
 File ruta = new File("C:/Users/android/Documents/gg/8.png");
           
            String d=(String.valueOf(ruta));
          
            Image foto= getToolkit().getImage(d);
            
           
          
           jLabel1.setIcon(new ImageIcon(foto));
}//GEN-LAST:event_txtD1MouseEntered

private void txtD2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtD2MouseEntered
 File ruta = new File("C:/Users/android/Documents/gg/9.png");
           
            String d=(String.valueOf(ruta));
          
            Image foto= getToolkit().getImage(d);
            
           
          
           jLabel1.setIcon(new ImageIcon(foto));// TODO add your handling code here:
}//GEN-LAST:event_txtD2MouseEntered

private void jreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jreActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jreActionPerformed

private void jchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchActionPerformed
PreparedStatement psd1,psd2,psd4;
  
      SQL2="UPDATE actividades set activo=? WHERE cedula=? ";
try{
     psd1 = cn.prepareStatement(SQL2);
     psd1.setString(1,acti);
        psd1.setString(2,cedu);
       
          
      
      psd1.executeUpdate();
        } catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Error");
        
    }   
   
    chofer1 d=new chofer1();
d.setVisible(true);

 SQL2="UPDATE actividades set activo=? WHERE cedula=? ";
try{
     psd2 = cn.prepareStatement(SQL2);
     psd2.setString(1,"0");
        psd2.setString(2,cedu);
       
          
      
      psd2.executeUpdate();
        } catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Error");
        
    }   
}//GEN-LAST:event_jchActionPerformed

private void jcsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcsActionPerformed

 
    
    
    PreparedStatement psd1,psd2,psd4;
  
      SQL2="UPDATE actividades set activo=? WHERE cedula=? ";
try{
     psd1 = cn.prepareStatement(SQL2);
     psd1.setString(1,acti);
        psd1.setString(2,cedu);
       
          
      
      psd1.executeUpdate();
        } catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Error");
        
    }   
   
   GestionActividad d=new GestionActividad();
d.setVisible(true);

 SQL2="UPDATE actividades set activo=? WHERE cedula=? ";
try{
     psd2 = cn.prepareStatement(SQL2);
     psd2.setString(1,"0");
        psd2.setString(2,cedu);
       
          
      
      psd2.executeUpdate();
        } catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Error");
        
    }      
}//GEN-LAST:event_jcsActionPerformed

private void jcdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcdActionPerformed
PreparedStatement psd1,psd2,psd4;
  
  
      SQL2="UPDATE actividades set activo=? WHERE cedula=? ";
try{
     psd1 = cn.prepareStatement(SQL2);
     psd1.setString(1,acti);
        psd1.setString(2,cedu);
       
          
      
      psd1.executeUpdate();
        } catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Error");
        
    }   
   
    ConsultaDinero d=new ConsultaDinero();
d.setVisible(true);

 SQL2="UPDATE actividades set activo=? WHERE cedula=? ";
try{
     psd2 = cn.prepareStatement(SQL2);
     psd2.setString(1,"0");
        psd2.setString(2,cedu);
       
          
      
      psd2.executeUpdate();
        } catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Error");
        
    }   // TODO add your handling code here:
}//GEN-LAST:event_jcdActionPerformed

private void jcssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcssActionPerformed
PreparedStatement psd1,psd2,psd4;
  
      SQL2="UPDATE actividades set activo=? WHERE cedula=? ";
try{
     psd1 = cn.prepareStatement(SQL2);
     psd1.setString(1,acti);
        psd1.setString(2,cedu);
       
          
      
      psd1.executeUpdate();
        } catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Error");
        
    }   
   
   CosultaServicio d=new CosultaServicio();
d.setVisible(true);

 SQL2="UPDATE actividades set activo=? WHERE cedula=? ";
try{
     psd2 = cn.prepareStatement(SQL2);
     psd2.setString(1,"0");
        psd2.setString(2,cedu);
       
          
      
      psd2.executeUpdate();
        } catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Error");
        
    } // TODO add your handling code here:
}//GEN-LAST:event_jcssActionPerformed

private void jcusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcusActionPerformed
PreparedStatement psd1,psd2,psd4;
  
      SQL2="UPDATE actividades set activo=? WHERE cedula=? ";
try{
     psd1 = cn.prepareStatement(SQL2);
     psd1.setString(1,acti);
        psd1.setString(2,cedu);
       
          
      
      psd1.executeUpdate();
        } catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Error");
        
    }   
   
    auditoria1 d=new auditoria1();
d.setVisible(true);

 SQL2="UPDATE actividades set activo=? WHERE cedula=? ";
try{
     psd2 = cn.prepareStatement(SQL2);
     psd2.setString(1,"0");
        psd2.setString(2,cedu);
       
          
      
      psd2.executeUpdate();
        } catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Error");
        
    } // TODO add your handling code here:
}//GEN-LAST:event_jcusActionPerformed

private void jusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jusuActionPerformed
rusuario c = new rusuario();
c.setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_jusuActionPerformed

private void jrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrActionPerformed
PreparedStatement psd1,psd2,psd4;
  
      SQL2="UPDATE actividades set activo=? WHERE cedula=? ";
try{
     psd1 = cn.prepareStatement(SQL2);
     psd1.setString(1,acti);
        psd1.setString(2,cedu);
       
          
      
      psd1.executeUpdate();
        } catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Error");
        
    }   
   
    control d=new control();
d.setVisible(true);

 SQL2="UPDATE actividades set activo=? WHERE cedula=? ";
try{
     psd2 = cn.prepareStatement(SQL2);
     psd2.setString(1,"0");
        psd2.setString(2,cedu);
       
          
      
      psd2.executeUpdate();
        } catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Error");
        
    } // TODO add your handling code here:
}//GEN-LAST:event_jrActionPerformed

    private void jInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInActionPerformed

    private void jmuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Thread(new Principal()).start();
            }
        });
    }
     public void run()
  {
    try
    {
      setVisible(true);
      for (int i = 0; i < 8; i++)
      {
        Thread.sleep(this.velocidad);
        setSize(this.x, this.y);
        setLocationRelativeTo(null);
        this.x += 106;
        if (this.x == 848) {
          for (int j = 0; j < 6; j++)
          {
            Thread.sleep(this.velocidad);
            setSize(this.x, this.y);
            setLocationRelativeTo(null);
            this.y += 100;
          }
        }
      }
    }
    catch (InterruptedException e) {}
  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuItem jIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem jcd;
    private javax.swing.JMenuItem jch;
    private javax.swing.JMenuItem jcs;
    private javax.swing.JMenuItem jcss;
    private javax.swing.JMenuItem jcus;
    private javax.swing.JMenuItem jmu;
    private javax.swing.JMenuItem jr;
    private javax.swing.JMenuItem jre;
    private javax.swing.JMenuItem jusu;
    private javax.swing.JButton txtC;
    private javax.swing.JButton txtCS;
    private javax.swing.JButton txtD;
    private javax.swing.JButton txtD1;
    private javax.swing.JButton txtD2;
    private javax.swing.JButton txtS;
    // End of variables declaration//GEN-END:variables
}
