/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * rusuario.java
 *
 * Created on 06/01/2017, 07:48:41 PM
 */
package trans.gru.pc;

import CBD.CBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author GeAnJi
 */
public class rusuario extends javax.swing.JFrame {
int Ac=0;
String co,co1;
CBD cc= new CBD();
Connection cn= cc.Conectar();

Statement st = null;  
    /** Creates new form rusuario */
    public rusuario() {
        initComponents();
         this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        Bloqueo();
    }
    void limpiar(){
    taxtce.setText("");
    txtap.setText("");
    txtcontraseña.setText("");
    txtnom.setText("");
    txttel.setText("");
    txtusu.setText(""); 
    boxSex.setSelectedItem("--Seleccione--");
    }
     void Bloqueo(){
    taxtce.setEnabled(false);
    txtap.setEnabled(false);
    txtcontraseña.setEnabled(false);
    txtnom.setEnabled(false);
    txttel.setEnabled(false);
    txtusu.setEnabled(false);
    boxSex.setEnabled(false);
    }
       void desbloqueo(){
    taxtce.setEnabled(true);
    txtap.setEnabled(true);
    txtcontraseña.setEnabled(true);
    txtnom.setEnabled(true);
    txttel.setEnabled(true);
    txtusu.setEnabled(true);
    boxSex.setEnabled(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txttel = new javax.swing.JTextField();
        txtusu = new javax.swing.JTextField();
        txtcontraseña = new javax.swing.JPasswordField();
        boxSex = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtap = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        taxtce = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnuevo = new javax.swing.JButton();
        bteli = new javax.swing.JButton();
        btguar = new javax.swing.JButton();
        btedi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(149, 200, 248));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DE USUARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        txttel.setFont(new java.awt.Font("Monospaced", 1, 14));
        txttel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        txtusu.setFont(new java.awt.Font("Monospaced", 1, 14));
        txtusu.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        txtcontraseña.setFont(new java.awt.Font("Monospaced", 1, 14));
        txtcontraseña.setText("jPasswordField2");
        txtcontraseña.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        boxSex.setFont(new java.awt.Font("Tahoma", 1, 11));
        boxSex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--SEXO--", "Femenino", "Masculino", "Otros" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONTRASEÑA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("USUARIO");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TELEFONO");

        jPanel3.setBackground(new java.awt.Color(20, 136, 238));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("NOMBRE");

        txtap.setFont(new java.awt.Font("Monospaced", 1, 14));
        txtap.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("APELLIDO");

        taxtce.setFont(new java.awt.Font("Monospaced", 1, 14));
        taxtce.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CEDULA");

        txtnom.setFont(new java.awt.Font("Monospaced", 1, 14));
        txtnom.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(txtnom, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                .addGap(3, 3, 3))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtap, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                            .addComponent(taxtce, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))
                        .addGap(3, 3, 3)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taxtce, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtap, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                    .addComponent(txtusu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                    .addComponent(txtcontraseña, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(boxSex, 0, 196, Short.MAX_VALUE)
                                .addGap(16, 16, 16))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .addComponent(txttel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                        .addGap(101, 101, 101)))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtusu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxSex, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jLabel7.setBackground(new java.awt.Color(149, 200, 248));
        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("GESTIÒN DE USUARIOS");
        jLabel7.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(149, 200, 248));

        btnuevo.setBackground(new java.awt.Color(0, 0, 0));
        btnuevo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        btnuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnuevo.setIcon(new javax.swing.ImageIcon("C:\\Users\\android\\Documents\\iconos\\plus.png")); // NOI18N
        btnuevo.setText("Nuevo");
        btnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuevoActionPerformed(evt);
            }
        });

        bteli.setBackground(new java.awt.Color(0, 0, 0));
        bteli.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        bteli.setForeground(new java.awt.Color(255, 255, 255));
        bteli.setIcon(new javax.swing.ImageIcon("C:\\Users\\android\\Documents\\iconos\\trash full.png")); // NOI18N
        bteli.setText("Eliminar");
        bteli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteliActionPerformed(evt);
            }
        });

        btguar.setBackground(new java.awt.Color(0, 0, 0));
        btguar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        btguar.setForeground(new java.awt.Color(255, 255, 255));
        btguar.setIcon(new javax.swing.ImageIcon("C:\\Users\\android\\Documents\\iconos\\install.png")); // NOI18N
        btguar.setText("Guardar");
        btguar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btguarActionPerformed(evt);
            }
        });

        btedi.setBackground(new java.awt.Color(0, 0, 0));
        btedi.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        btedi.setForeground(new java.awt.Color(255, 255, 255));
        btedi.setIcon(new javax.swing.ImageIcon("C:\\Users\\android\\Documents\\iconos\\edit.png")); // NOI18N
        btedi.setText("Editar");
        btedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btediActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btguar, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btedi, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addComponent(bteli, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btguar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bteli, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btedi, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9))
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btguarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btguarActionPerformed
String cedu,nom,ape,sexo,tele,usu,con,carg="NINGUNO";
String a1="0", b1="0", c1="0", d1="0",e1="0", f1="0",act="0";
String an="0",ag="0",ae="0",ael="0",bn="0",bg="0",be="0",bel="0",cn1="0",cg="0",ce="0",cel="0",dn="0",dg="0",de="0",del="0",acti="0";
cedu=taxtce.getText();
usu=txtusu.getText();
con=txtcontraseña.getText();

sexo=String.valueOf(boxSex.getSelectedItem());
nom=txtnom.getText();
ape=txtap.getText();

 tele=txttel.getText();
String SQL1,SQL2,SQL3;




PreparedStatement psd,psd1,psd2;
switch(Ac){
   
    case 1:
        try{
             if((cedu.isEmpty())||(usu.isEmpty())||(con.isEmpty())||(nom.isEmpty())||(ape.isEmpty())||(tele.isEmpty()))
       {
          
           
         JOptionPane.showMessageDialog(null,"Por favor llene todos los campos.!");
       }
       else
       {
         
             Statement st2 = this.cn.createStatement();
        ResultSet rs = st2.executeQuery("SELECT * FROM usuarios WHERE cedula ='" + cedu + "'");
        rs.last();
        int encontrado = rs.getRow();
        if (encontrado == 1)
        {
          JOptionPane.showMessageDialog(null, "Cedula existente");
        }
        else
        {
        SQL1="INSERT INTO usuarios (cedula,nombres,apellidos,sexo,telefono,usuario,contraseña,cargo) VALUES (?,?,?,?,?,?,?,?)";
   
        psd=cn.prepareStatement(SQL1);
         psd.setString(1,cedu);
        psd.setString(2,nom);
        psd.setString(3,ape);
         psd.setString(4,sexo);
          psd.setString(5,tele);
           psd.setString(6,usu);
            psd.setString(7,con);
             psd.setString(8,carg);
           
           int Up=psd.executeUpdate();
           if(Up==1){
              limpiar();
Bloqueo(); 
          JOptionPane.showMessageDialog(null,"GUARDADO EXITOSO");   
             
           }
          SQL2="INSERT INTO rol (cedula,a,b,c,d,e,f,activo) VALUES (?,?,?,?,?,?,?,?)";
    try{
        psd1=cn.prepareStatement(SQL2);
         psd1.setString(1,cedu);
        psd1.setString(2,a1);
        psd1.setString(3,b1);
         psd1.setString(4,c1);
          psd1.setString(5,d1);
          psd1.setString(6,e1);
          psd1.setString(7,f1);
           psd1.setString(8,act);
           
           
          psd1.executeUpdate();
          
              
        }catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Error tabla rol");
      } 
      SQL3="INSERT INTO actividades (AN,AG,AE,AEL,BN,BG,BE,BEL,CN,CG,CE,CEL,DN,DG,DE,DEL,cedula,activo) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ";
try{
     psd1 = cn.prepareStatement(SQL3);
     psd1.setString(1,an);
        psd1.setString(2,ag);
        psd1.setString(3,ae);
         psd1.setString(4,ael);
         psd1.setString(5,bn);
        psd1.setString(6,bg);
        psd1.setString(7,be);
         psd1.setString(8,bel);
         psd1.setString(9,cn1);
        psd1.setString(10,cg);
        psd1.setString(11,ce);
         psd1.setString(12,cel);
         psd1.setString(13,dn);
        psd1.setString(14,dg);
        psd1.setString(15,de);
         psd1.setString(16,del);
          psd1.setString(17,cedu);
          psd1.setString(18,acti);
          
          
      
      psd1.executeUpdate();
        } catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Error tabla actividades");
        
    } }}

    }catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Verifique los campos");
        
    }
    break;
    case 2:
        try{
             if((cedu.isEmpty())||(usu.isEmpty())||(con.isEmpty())||(nom.isEmpty())||(ape.isEmpty())||(tele.isEmpty()))
       {
          
           
         JOptionPane.showMessageDialog(null,"Por favor llene todos los campos.!");
       }
       else
       {
        SQL1="UPDATE usuarios set cedula=?,nombres=?,apellidos=?,sexo=?,telefono=?,usuario=?,contraseña=? WHERE codigo=? ";

     psd = cn.prepareStatement(SQL1);
     psd.setString(1,cedu);
        psd.setString(2,nom);
        psd.setString(3,ape);
         psd.setString(4,sexo);
          psd.setString(5,tele);
           psd.setString(6,usu);
            psd.setString(7,con);
       psd.setString(8,co);
           int n=psd.executeUpdate();
           
           if(n>0){
          limpiar();
Bloqueo(); 
          JOptionPane.showMessageDialog(null,"GUARDADO EXITOSO");   
              
              
           }
            SQL2="UPDATE rol set cedula=? WHERE codigo=? ";
try{
     psd1 = cn.prepareStatement(SQL2);
      psd1.setString(1,cedu);
       psd1.setString(2,co1); 
      
       psd1.executeUpdate();
        
      } catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Error en cedula rol");
        
    }     
} }catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Error");
        
    }
    break;
      }  
    

}//GEN-LAST:event_btguarActionPerformed

private void btnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuevoActionPerformed
Ac=1;
desbloqueo();
limpiar();
}//GEN-LAST:event_btnuevoActionPerformed

private void btediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btediActionPerformed
String SQL1,cod,cod2;

Ac=2;
 cod= JOptionPane.showInputDialog("Usuario:");
  cod2= JOptionPane.showInputDialog("Contraseña:");
  
try{
     if(( cod.isEmpty())||( cod2.isEmpty()))
       {
          
           
         JOptionPane.showMessageDialog(null,"Por favor llene todos los campos.!");
       }
       else
       {
         
    
   SQL1="SELECT * FROM usuarios WHERE usuario ='"+cod+"' AND  contraseña='"+cod2+"' ";
    
   st = this.cn.createStatement();
           ResultSet rs = st.executeQuery(SQL1);
           rs.next();
           desbloqueo();
limpiar();
            co=rs.getString("codigo");
          taxtce.setText(rs.getString("cedula"));
          String c =taxtce.getText();
            
        boxSex.setSelectedItem(rs.getString("sexo"));
  
   txtnom.setText(rs.getString("nombres"));
  
  
   txtap.setText(rs.getString("apellidos"));
   txttel.setText(rs.getString("telefono"));
   
   txtusu.setText(rs.getString("usuario"));
   txtcontraseña.setText(rs.getString("contraseña"));
   String SQL2="SELECT * FROM rol WHERE cedula ='"+c+"'  ";
       st = this.cn.createStatement();
           ResultSet rs1 = st.executeQuery(SQL2);
           rs1.next();
           co1=(rs1.getString("codigo")); 
           
      
}

  }catch (SQLException ex) {}
  
 
}//GEN-LAST:event_btediActionPerformed

private void bteliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteliActionPerformed
String SQL1,cod,cod2;

Ac=2;
 cod= JOptionPane.showInputDialog("Usuario:");
  cod2= JOptionPane.showInputDialog("Contraseña:");

    try{
     if(( cod.isEmpty())||( cod2.isEmpty()))
       {
          
           
         JOptionPane.showMessageDialog(null,"Por favor llene todos los campos.!");
       }
       else
       {
    
   SQL1="SELECT * FROM usuarios WHERE usuario ='"+cod+"' AND  contraseña='"+cod2+"' ";
      
   st = this.cn.createStatement();
           ResultSet rs = st.executeQuery(SQL1);
           rs.next();
            desbloqueo();
            co=rs.getString("codigo");
            taxtce.setText(rs.getString("cedula"));
        boxSex.setSelectedItem(rs.getString("sexo"));
  
   txtnom.setText(rs.getString("nombres"));
  
  
   txtap.setText(rs.getString("apellidos"));
   txttel.setText(rs.getString("telefono"));
   
   txtusu.setText(rs.getString("usuario"));
   txtcontraseña.setText(rs.getString("contraseña"));
   
    int resp= JOptionPane.showConfirmDialog(this, "Deseas Eliminarlo","Eliminar Dato",JOptionPane.YES_NO_OPTION);

            if(resp==JOptionPane.YES_NO_OPTION){
                try{
                    PreparedStatement psd=null;
                    SQL1 =" DELETE FROM usuarios WHERE codigo= '"+co+"'  ";
                    psd=cn.prepareStatement(SQL1);
                    psd.execute();
                    psd.close();
                     limpiar();
Bloqueo();
                    JOptionPane.showMessageDialog(null,"REGISTRO ELIMINADO");
                }    catch (SQLException ex) {}
}

  }}catch (SQLException ex) {}
 
}//GEN-LAST:event_bteliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rusuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rusuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rusuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rusuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new rusuario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox boxSex;
    private javax.swing.JButton btedi;
    private javax.swing.JButton bteli;
    private javax.swing.JButton btguar;
    private javax.swing.JButton btnuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField taxtce;
    private javax.swing.JTextField txtap;
    private javax.swing.JPasswordField txtcontraseña;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txttel;
    private javax.swing.JTextField txtusu;
    // End of variables declaration//GEN-END:variables
}
